# Generated by Django 3.2.9 on 2021-12-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='默认值', max_length=100, verbose_name='标题'),
        ),
    ]
