# Generated by Django 3.2.9 on 2021-12-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20211214_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_file',
            field=models.FileField(null=True, upload_to='note_file', verbose_name='文件'),
        ),
    ]
