# Generated by Django 3.2.9 on 2021-12-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户-客户端'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uesername',
            new_name='username',
        ),
    ]
